#### Fs ####

FsRouterAnchor: &FsRouterAnchor
  rule: "HostRegexp(`^.+\\.fs\\.cn$`) || Host(`fs.cn`) && Path(`/robots.txt`)"
  service: FsSvc
  middlewares:

#### Http ####

http:
  services:
    FsSvc:
      loadBalancer:
        servers:
          - url: "http://fs:80"

  middlewares:

  routers:

    #### fs ####

    FsHttp:
      <<: *FsRouterAnchor
      entryPoints:
        - web
      priority: 100

        