api:
  insecure: true
  dashboard: true
ping:
  entryPoint: traefik
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  ssh:
    address: ":22"
  traefik:
    address: ":8082"
  phpInnerApi:
    address: ":8242"
  phpRpc:
    address: ":8383"

providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
    network: "zn-backend"
  file:
    directory: "/etc/traefik/config"
    watch: true

log:
  level: DEBUG
  format: json
  
accessLog:
  format: "json"
  fields:
    headers:
      defaultMode: keep
      